brace_style = "SameLineWhere"
fn_params_layout = "Tall"
max_width = 220
comment_width = 220
wrap_comments = true
format_code_in_doc_comments = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

empty_item_single_line = false
inline_attribute_width = 0

indent_style = "Block"
tab_spaces = 4
hard_tabs = false

newline_style = "Unix"

merge_derives = true
skip_children = false
style_edition = "2021"
format_strings = true
